// GENERATED from the Rust types by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * The household: every Sustain, the selection, and where the log lives.
 */
async getWorld() : Promise<WorldDto> {
    return await TAURI_INVOKE("get_world");
},
/**
 * `Σ` and current state for one Sustain — the selected one when `id` is absent.
 */
async getSustain(id: string | null) : Promise<SustainDto | null> {
    return await TAURI_INVOKE("get_sustain", { id });
},
/**
 * Point the cockpit at a different Sustain. `false` when there is no such id.
 */
async selectSustain(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_sustain", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Instantiate a new Sustain. `false` when the id is already taken.
 */
async createSustain(id: string, label: string, template: TemplateId, parent: string | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_sustain", { id, label, template, parent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ★★★ Ask the engine to do something on one Sustain, and report the verdict.
 * 
 * Returns `GateResult` — **not** an error type. A refusal is a correct answer,
 * and typing it as an error would make the UI render the system working as the
 * system failing.
 * 
 * `None` means there is no such Sustain, which is a different fact from a
 * refusal and is kept a different shape. The outer `Result` is for the disk.
 */
async runOperator(sustainId: string, operator: string, params: JsonValue) : Promise<Result<GateResult | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_operator", { sustainId, operator, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `V` for one Sustain, evaluated now.
 */
async getConstraints(sustainId: string) : Promise<ConstraintReading[]> {
    return await TAURI_INVOKE("get_constraints", { sustainId });
},
/**
 * ★★ The persisted log — the event log a person can read.
 * 
 * Read from **disk**, not from memory: what this shows is what actually
 * survives, which is the only version worth showing.
 */
async getLog(sustainId: string) : Promise<Result<LogEntryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log", { sustainId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every operator the given Sustain may actually run, with its **measured** cost.
 * 
 * ★★ The list is the Sustain's own `T`, not the whole registry — an operator a
 * definition does not permit would be refused with `operator_allowed`, and
 * offering it would be inviting a refusal the person could not have predicted.
 */
async getOperators(sustainId: string) : Promise<OperatorDto[]> {
    return await TAURI_INVOKE("get_operators", { sustainId });
},
/**
 * ★★★ Run a hypothetical branch. **Nothing is written.**
 * 
 * The fork is `state.clone()` plus the same `execute_admitted` a real call
 * uses, so a step refused here is refused for the same reason it would be for
 * real. It touches no log, no ledger and no meter.
 */
async simulate(sustainId: string, steps: ([string, JsonValue])[]) : Promise<Branch | null> {
    return await TAURI_INVOKE("simulate", { sustainId, steps });
},
/**
 * The whole economy, read from the engine's own ledger and parameters.
 */
async getEconomy() : Promise<EconomyDto> {
    return await TAURI_INVOKE("get_economy");
},
/**
 * ★★★ Change a governed parameter — through the gate, like anything else.
 * 
 * Returns the gate's verdict: an out-of-range value is refused with
 * `enforcement_gate`, the same reason a household breach gives.
 */
async setParameter(name: string, value: number) : Promise<GateResult> {
    return await TAURI_INVOKE("set_parameter", { name, value });
},
/**
 * Every definition a person has authored on this host.
 */
async getDefinitions() : Promise<AuthoredDefinition[]> {
    return await TAURI_INVOKE("get_definitions");
},
/**
 * ★★★ Author a definition — **the engine decides whether it lands**.
 * 
 * `editing::typecheck` parses every invariant and binds it against the schema;
 * `editing::safe` checks it against every live instance. A definition that
 * fails either is never written, and the verdict carries the engine's own
 * words rather than a summary of them.
 */
async authorDefinition(definition: AuthoredDefinition) : Promise<Result<DefinitionVerdict, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("author_definition", { definition }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Instantiate a Sustain from an authored definition — the same path a
 * built-in uses.
 */
async createFromDefinition(id: string, label: string, definitionId: string, parent: string | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_from_definition", { id, label, definitionId, parent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the local principal may do on one Sustain, **as the engine judges it**.
 * 
 * ★★ `permitted` walks the membership path with the weakest-link rule and
 * compares against each operator's declared `min_privilege`. This is the real
 * model, not a display of intentions.
 * 
 * ★★★ **And it IS what the gate checks.** Every call runs
 * `Authorization::Principal` with the unlocked identity, so this is authority
 * in force. It asks the same `permitted` the gate asks, from the same
 * memberships and the same path — a screen computing permission its own way
 * would eventually disagree with the thing that decides.
 */
async getAccess(sustainId: string) : Promise<AccessDto> {
    return await TAURI_INVOKE("get_access", { sustainId });
},
/**
 * **ρ** for one Sustain — its declared totals, folded fresh from its own state
 * and every linked child's.
 * 
 * ★ `None` only when there is no such Sustain. A Sustain that declares no
 * aggregates answers with an empty reading, because *asked for no totals* and
 * *a total that could not be computed* are different facts.
 */
async getRollup(sustainId: string) : Promise<RollupDto | null> {
    return await TAURI_INVOKE("get_rollup", { sustainId });
},
/**
 * ★★★ **The atomic, conserved cross-Sustain transfer.**
 * 
 * Both legs commit or neither does — the core makes half a transfer
 * unrepresentable, and the store's write-ahead journal makes it unwritable.
 * 
 * A refusal comes back as a **value**, not an error: the gate declining is an
 * expected outcome, and turning it into a thrown error would put it in the
 * same bucket as a disk failure.
 */
async transfer(fromSustainId: string, toSustainId: string, path: string, amount: number) : Promise<Result<TransferResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer", { fromSustainId, toSustainId, path, amount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Who this machine is, and whether the key is unlocked.
 */
async getIdentity() : Promise<IdentityDto> {
    return await TAURI_INVOKE("get_identity");
},
/**
 * **Unlock** the local identity with a passphrase.
 * 
 * ★★★ The passphrase is not compared against anything. It derives a key, and
 * either that key decrypts the private half or it does not — there is no
 * branch here an attacker could invert, and a wrong passphrase leaves the
 * world locked. The error text is the same for a wrong passphrase and a
 * tampered file, on purpose.
 */
async unlockIdentity(passphrase: string) : Promise<Result<IdentityDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_identity", { passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Enrol** a new identity on a machine that has none.
 */
async enrolIdentity(handle: string, passphrase: string) : Promise<Result<IdentityDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enrol_identity", { handle, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop the private key from memory. ★ Not a UI state — the key genuinely
 * leaves, so a locked cockpit cannot act even if a surface forgot to stop it.
 */
async lockIdentity() : Promise<IdentityDto> {
    return await TAURI_INVOKE("lock_identity");
},
/**
 * The capture queue, the declared sources, and the rules in force.
 */
async getIngest(sustainId: string) : Promise<Result<IngestDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ingest", { sustainId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Capture one message.**
 * 
 * ★★★ A message carrying a secret is refused **before anything is written**
 * — the result has no message field at all, because there is nothing to show.
 * A mapped message applies through the same gated path the Console uses, as
 * the unlocked principal.
 */
async captureMessage(sustainId: string, sourceId: string, raw: string) : Promise<Result<CaptureResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_message", { sustainId, sourceId, raw }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Declare a capture source, optionally with the cadence it should keep.
 */
async declareSource(id: string, label: string, expectedIntervalMinutes: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("declare_source", { id, label, expectedIntervalMinutes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark a queued message as handled by a person.
 */
async resolveMessage(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_message", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Remember this format** — synthesise a rule from a confirmed correction.
 * 
 * ★★ Verified before it is ever added: it must be well-typed, must match the
 * message that taught it, and must not capture a message an existing rule
 * already handles. ★★★ A learned SPEND rule carries no operator, so a
 * correction can never teach the system to spend on someone's behalf.
 */
async learnRule(messageId: string, operator: string, params: JsonValue) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("learn_rule", { messageId, operator, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ★★★ Resolve a proposal with the engine's own `council::resolve`.
 * 
 * Real: the rule that a person's vote overrides the council, that an abstaining
 * person leaves it **in voting** rather than deciding, and that collected votes
 * with nobody in favour fail. None of it is re-implemented here.
 */
async resolveProposal(votes: ([string, string, number])[], userVote: string | null, votesCollected: boolean) : Promise<CouncilOutcomeDto> {
    return await TAURI_INVOKE("resolve_proposal", { votes, userVote, votesCollected });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
committed: Committed,
refused: Refused,
rolledUp: RolledUp
}>({
committed: "committed",
refused: "refused",
rolledUp: "rolled-up"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The principal's authority over one Sustain.
 */
export type AccessDto = { principal: string; sustainId: string; 
/**
 * Effective privilege after the weakest-link path walk. `null` when the
 * principal has no membership at all.
 */
tier: number | null; memberships: number; operators: OperatorAccessDto[]; 
/**
 * ★★★ Whether the gate is currently checking any of this. It is not.
 */
enforced: boolean; note: string }
/**
 * One declared aggregate, answered by the engine.
 */
export type AggregateDto = { id: string; childPath: string; 
/**
 * `SUM` | `COUNT` | `AVG` | `MIN` | `MAX`.
 */
op: string; 
/**
 * ★ `null` for `MIN`/`MAX` over nothing — there is no smallest element of
 * an empty set, and `0` would be a claim.
 */
value: number | null; 
/**
 * ★ Whether ANYTHING was readable. `sum` over nothing is `0`, which is
 * arithmetically right and still not a measurement — a surface uses this
 * to say so rather than print a confident zero.
 */
grounded: boolean; included: ContributionDto[]; excluded: ExclusionDto[]; includesHouseholdOwn: boolean }
/**
 * A definition as authored and persisted.
 */
export type AuthoredDefinition = { id: string; label: string; dimensions: DimDecl[]; operators: string[]; invariants: InvariantDecl[]; 
/**
 * The opening state a new instance starts from.
 */
openingState: JsonValue }
/**
 * A whole hypothetical branch.
 */
export type Branch = { sustainId: string; steps: BranchStep[]; 
/**
 * ★ Always true. Carried so a surface cannot render a branch without being
 * handed the fact that it is one.
 */
hypothetical: boolean; 
/**
 * The state the branch started from, for a diff.
 */
from: JsonValue }
/**
 * One step of a hypothetical branch.
 * 
 * ★★★ **Nothing here was written.** A fork is `state.clone()` plus the same
 * `execute_admitted` a real call uses, so a step refused here would be refused
 * for real — with the same reason. It touches no log, no ledger and no meter.
 */
export type BranchStep = { operator: string; verdict: Verdict; reason: string | null; constraintViolated: string | null; mutations: number; events: EventDto[]; 
/**
 * The hypothetical state after this step.
 */
state: JsonValue }
/**
 * What one capture did, on the wire.
 */
export type CaptureResult = 
/**
 * ★★★ No message field at all: there is nothing to render, because
 * there was nothing to store.
 */
{ kind: "rejected"; reason: string } | { kind: "duplicate"; message: MessageDto } | { kind: "stored"; message: MessageDto }
export type ChildStatusDto = { sustainId: string; label: string; readable: boolean }
/**
 * ★★★ **A committed change, pushed.** One message per real change.
 * 
 * The event *is* the message: there is no tick, no sampler and no clock,
 * because the core has none and a sampler would manufacture events nothing
 * caused. A **refusal emits nothing** — the fold stays the truth, and a
 * message saying "nothing happened" would be a change that did not happen.
 * 
 * ★★ It carries the new state as well as the events, so a subscriber is
 * correct after a single message without replaying anything. The honest cost
 * is size: a large Sustain ships its whole state per change. That is fine for
 * a household and is named in the README rather than discovered later.
 */
export type Committed = { sustainId: string; operator: string; 
/**
 * Its position in the append-only log — the same `seq` on disk.
 */
seq: number; events: EventDto[]; mutations: number; state: JsonValue; 
/**
 * `V` re-evaluated after the change, by the engine.
 */
constraints: ConstraintReading[]; liquid: number | null }
/**
 * One invariant, evaluated against current state **by the engine**.
 * 
 * ★★ `holds` and `reason` come from `sustena_core::predicate::check`, the same
 * evaluator the gate uses. The host does not judge a rule; it asks.
 */
export type ConstraintReading = { id: string; expression: string; holds: boolean; 
/**
 * ★ Empty when it holds; otherwise the engine's own words, naming the
 * operand and the value that failed.
 */
reason: string }
/**
 * One contributor to a household total.
 * 
 * ★★ `isHousehold` is a real distinction, not decoration: a surface has to be
 * able to say *the household's own 6,600 plus six members* rather than listing
 * seven anonymous numbers, and inferring it by comparing ids would be the kind
 * of guess this layer exists to remove.
 */
export type ContributionDto = { sustainId: string; 
/**
 * The member's name, else the slot, else the id.
 */
label: string; isHousehold: boolean; value: number }
/**
 * What `council::resolve` decided.
 */
export type CouncilOutcomeDto = { 
/**
 * `Passed` | `Failed` | `InVoting` | `OverriddenByUser` | …
 */
status: string; 
/**
 * The councillor's single vote after `aggregate_delegated_votes`.
 */
aggregated: string; 
/**
 * The engine's own explanation of the aggregation.
 */
reasoning: string; utility: number; counted: number }
/**
 * What the engine said about an authored definition.
 */
export type DefinitionVerdict = 
/**
 * `typecheck` accepted it, and no live instance would be stranded.
 */
{ kind: "accepted" } | 
/**
 * ★ One entry per problem, each naming the invariant and the detail —
 * `editing::typecheck`'s own words, not a summary of them.
 */
{ kind: "notWellTyped"; errors: string[] } | 
/**
 * ★★ Live Sustains this edit would push outside their viable region —
 * each with the RULE it would break and the engine's reason. A refusal
 * that cannot say which sustain and which rule is an alarm, not a
 * diagnosis.
 */
{ kind: "wouldStrand"; instances: string[] }
/**
 * One dimension a person declared.
 */
export type DimDecl = { path: string; 
/**
 * `number` | `text` | `bool` | `any`.
 */
kind: string; 
/**
 * ★ Optional bounds for a number. `DimType::Number` carries them, so a
 * dimension can be constrained at the SCHEMA level as well as by an
 * invariant — two different questions: what values are representable, and
 * what values are viable.
 */
lo: number | null; hi: number | null }
/**
 * The whole economy, as one screen reads it.
 */
export type EconomyDto = { principal: string; balance: number; 
/**
 * `Sigma(mints) - Sigma(debits)`, transfers at zero.
 */
circulation: number; mintedTotal: number; issuedTotal: number; genesisId: string; genesisTotal: number; 
/**
 * ★ The audit is the engine's, not the host's: it names foreign mints,
 * mismatched allocations and undeclared principals rather than returning a
 * boolean.
 */
auditClean: boolean; auditDescribes: string; entries: LedgerEntryDto[]; parameters: ParameterDto[]; 
/**
 * Every reading the meter has taken, by operator.
 */
metered: ([string, MeasuredPawa])[]; 
/**
 * ★★★ The permanent boundary, carried as data so a surface cannot forget
 * to show it.
 */
boundaryNotice: string }
/**
 * One event the call published.
 */
export type EventDto = { name: string; payload: JsonValue }
/**
 * A contributor that could NOT be read, and the engine's own reason.
 * 
 * ★★★ This is the honest-exclusion contract on the wire. A total that dropped
 * a member silently would be indistinguishable from one where that member
 * genuinely holds nothing — so the exclusions travel with the value, and a
 * screen showing one without the other is misreporting on its own account.
 */
export type ExclusionDto = { sustainId: string; label: string; isHousehold: boolean; reason: string }
/**
 * The gate's own words about one call.
 */
export type GateResult = { verdict: Verdict; 
/**
 * The operator that was asked for.
 */
operator: string; 
/**
 * ★ The refusal reason, **as the engine wrote it**. Never re-phrased here:
 * the engine names the rule and the numbers, and a host that softened that
 * into "could not complete" would be hiding the only useful part.
 */
reason: string | null; 
/**
 * Which rule refused it — a guard expression, or `enforcement_gate`.
 */
constraintViolated: string | null; 
/**
 * Empty on a refusal, always — a refusal changes nothing.
 */
mutations: number; events: EventDto[]; 
/**
 * The resulting state, or the **untouched original** if refused.
 */
state: JsonValue }
/**
 * Whether the composition tree holds, **as the engine judges it**.
 * 
 * ★ A sum type rather than a bool: a tree that does not hold should say which
 * link broke it, and a `false` with the reason thrown away is an alarm rather
 * than a diagnosis.
 */
export type Holarchy = 
/**
 * `MonitorEngine::flatten_holarchy` accepted it — no duplicate id, no
 * unknown parent, no cycle.
 */
{ kind: "holds"; linked: number } | 
/**
 * It refused, and here is what it said.
 */
{ kind: "broken"; reason: string }
/**
 * Who this machine is, and whether the key is in memory.
 * 
 * ★★ `handle` is readable while LOCKED — a person should be able to see which
 * identity they are being asked to unlock. `publicKey` is not: it is derived
 * from the private half, and having it means the unlock genuinely happened.
 */
export type IdentityDto = { 
/**
 * Whether an identity exists on this machine at all.
 */
enrolled: boolean; 
/**
 * Whether the private key is in memory right now.
 */
unlocked: boolean; handle: string | null; 
/**
 * The verifying key, hex — present only once unlocked.
 */
publicKey: string | null; 
/**
 * The KDF actually in force, named rather than assumed.
 */
kdf: string | null; iterations: number | null }
/**
 * The whole ingest picture for one Sustain.
 */
export type IngestDto = { messages: MessageDto[]; sources: SourceDto[]; rules: RuleDto[]; 
/**
 * ★★★ How many messages were refused for carrying a secret. A COUNT,
 * and nothing else — the messages themselves were never written.
 */
rejected: number; needsAttention: number }
/**
 * One rule a person declared.
 */
export type InvariantDecl = { id: string; expression: string }
/**
 * A rule the household declared it must stay within.
 */
export type InvariantDto = { id: string; expression: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * One line of the juul ledger.
 * 
 * ★★ The **kind** is the entry's own variant, not a sign on a number: a mint
 * names the declaration that authorised it, a debit names the run it paid for,
 * a transfer names both ends. Collapsing them would make *where did this juul
 * come from* unanswerable.
 */
export type LedgerEntryDto = { 
/**
 * `mint` | `debit` | `transfer`.
 */
kind: string; principal: string; counterparty: string | null; amount: number; 
/**
 * For a mint: the declaration that authorised it. For a debit: the operator.
 */
authority: string; 
/**
 * Its effect on total circulation — `+` for a mint, `-` for a debit, `0` for a transfer.
 */
circulationDelta: number }
/**
 * One line of the persisted log, as a person reads it.
 */
export type LogEntryDto = { seq: number; 
/**
 * The operator that caused it, or `genesis` for the opening line.
 */
operator: string; events: EventDto[]; 
/**
 * ★ How many state changes it carried. The mutations themselves stay on
 * disk — a log view is for reading what happened, and a wall of paths is
 * not that.
 */
mutations: number }
/**
 * What the meter has actually measured for an operator.
 * 
 * ★★★ `None` means **not measured**, and the UI must say so rather than
 * showing a zero. A `0` from an unmeasured basis is silence, not cheapness.
 */
export type MeasuredPawa = { runs: number; meanPawa: number; totalPawa: number; totalCompute: number; totalStorage: number }
/**
 * One captured message.
 * 
 * ★★★ A REJECTED message never appears here, because it never reached the
 * store. The queue counts them and holds none of them.
 */
export type MessageDto = { id: string; sourceId: string; 
/**
 * `mapped` | `parsed_unmapped` | `informational` | `unparsed`.
 */
status: string; 
/**
 * Which declared rule handled it — empty when none did.
 */
parserName: string; 
/**
 * The engine's own words about why this is what it is.
 */
reason: string; 
/**
 * The raw text. Retained deliberately: a person correcting a
 * classification needs to see what actually arrived.
 */
rawPayload: string; amount: number | null; counterparty: string | null; direction: string | null; externalRef: string | null; operator: string | null; applied: boolean; 
/**
 * What the gate said, when a mapped message was refused.
 */
gateReason: string | null; resolved: boolean; needsAttention: boolean }
/**
 * Whether the principal may run one operator, as the engine judges it.
 */
export type OperatorAccessDto = { operator: string; 
/**
 * The operator's declared `min_privilege`. ★ Lower is more privileged:
 * 0 = owner, 3 = observer.
 */
requiredTier: number; permitted: boolean; 
/**
 * The engine's own denial text when it is not.
 */
denial: string | null }
/**
 * One operator the selected Sustain may actually run.
 */
export type OperatorDto = { name: string; description: string; params: ParamDto[]; 
/**
 * The author's declared estimate. ★ Kept beside the measurement precisely
 * so the two can be compared — the reference's estimate is usually 0.
 */
declaredPawa: number; 
/**
 * ★ `null` when the meter has never seen it run.
 */
measured: MeasuredPawa | null; sideEffects: string[] }
/**
 * One parameter an operator declares.
 * 
 * ★★ **Declared by the operator, not guessed by the UI.** `ParamDecl` carries
 * the name, the kind, whether it is required, and — for a naming parameter —
 * the state path whose KEYS are the legal values. So a picker can offer real
 * pocket names without this app knowing what a pocket is.
 */
export type ParamDto = { name: string; 
/**
 * `number` | `text` | `any`.
 */
kind: string; required: boolean; 
/**
 * A state path whose keys are the legal values, when the operator declares one.
 */
namesWithin: string | null }
/**
 * One governed parameter and its declared bounds.
 */
export type ParameterDto = { name: string; value: number; genesis: number; min: number; max: number }
/**
 * A pocket, at summary scale.
 * 
 * ★ Small on purpose. The Constellation reads summaries for every Sustain and
 * hydrates full state only on drill-in, so this carries the three numbers a
 * vitals reading needs and not the document they came from.
 */
export type PocketSummary = { name: string; allocated: number; spent: number }
/**
 * ★★★ **A refusal, pushed — and it carries NO STATE.**
 * 
 * A separate type from [`Committed`] on purpose. The two answer different
 * questions: *what changed* and *what was asked and declined*. Collapsing them
 * into one message with a verdict flag would make it possible for a consumer
 * to treat a refusal as a change by forgetting to branch — here there is no
 * `state` field to read, so that mistake is unspellable.
 * 
 * ★★ This does not weaken V1.2's rule. **A refusal still emits no state
 * delta**; the fold is still the only truth about state. What travels here is
 * the *activity*: a request happened and the gate declined it, which a person
 * watching a household genuinely wants to see.
 */
export type Refused = { sustainId: string; operator: string; 
/**
 * The engine's own words.
 */
reason: string | null; 
/**
 * Which rule declined it.
 */
constraintViolated: string | null }
/**
 * ★★★ **A household total, recomputed and pushed.**
 * 
 * A THIRD typed event, for the same reason there is a second: it answers a
 * third question. `Committed` says *what changed, in the Sustain that
 * changed*; ρ is a **different Sustain's** derived reading, and folding it
 * into `Committed` would mean a message about Bonnie's habitat carrying the
 * homestead's state under a field name that did not say so.
 * 
 * ★★ It is emitted only after a real commit, only for a Sustain that actually
 * declares aggregates. A refusal emits nothing here either — ρ is a function
 * of state, and a refused call changed no state, so the total it would carry
 * is the one the subscriber already has.
 */
export type RolledUp = { rollup: RollupDto }
/**
 * **ρ** for one parent, computed fresh.
 * 
 * ★ `declared` is empty for a Sustain that asked for no totals — which is a
 * different fact from *a total that could not be computed*, and the two must
 * not render the same.
 */
export type RollupDto = { sustainId: string; aggregates: AggregateDto[]; 
/**
 * Linked children, and whether each was readable at all.
 */
children: ChildStatusDto[] }
/**
 * One declared parse rule, for the library view.
 */
export type RuleDto = { id: string; source: string; version: number; 
/**
 * `mapped` | `parsed_unmapped` | `informational`.
 */
status: string; operator: string | null; 
/**
 * `shipped` | `user_corrected` | `proposed_confirmed`.
 */
trust: string; examples: number }
/**
 * A declared capture source.
 */
export type SourceDto = { id: string; label: string; captures: number; 
/**
 * ★ `null` when this source declared no cadence — and then `stale` is
 * `false`, never a guess.
 */
expectedIntervalMinutes: number | null; everSeen: boolean }
/**
 * `Σ = ⟨B, S, V, T, ⊕⟩`, as much of it as a cockpit needs to draw.
 * 
 * ★ Deliberately not the whole `Definition`: a walking skeleton should carry
 * what it actually renders, and inventing fields the UI does not use yet would
 * be publishing a contract nobody has tested.
 */
export type SustainDto = { id: string; label: string; 
/**
 * `T` — the moves this Sustain may make.
 */
operators: string[]; 
/**
 * `V` — the viable region.
 */
invariants: InvariantDto[]; 
/**
 * Whether the gate is armed for it.
 */
gateArmed: boolean; 
/**
 * `S` — current state.
 */
state: JsonValue }
/**
 * One Sustain, as a selector row needs it.
 * 
 * ★ Deliberately not the full `SustainDto`: a list of six should not carry six
 * full state documents, and a shape that made it easy to would invite it.
 */
export type SustainSummary = { id: string; label: string; template: TemplateId; 
/**
 * `⊕` — its parent, if it has one.
 */
parent: string | null; 
/**
 * How many events its log holds. ★ The real number, folded from disk —
 * this is what makes persistence visible rather than claimed.
 */
events: number; 
/**
 * Its liquid balance, or `null` when the Sustain declares no such
 * dimension. **Never 0 for absent** — a missing figure renders as "—".
 */
liquid: number | null; 
/**
 * Its pockets, at summary scale.
 */
pockets: PocketSummary[]; 
/**
 * ★★ `V` for THIS Sustain, evaluated by the engine — so a constellation
 * can show a broken rule anywhere without hydrating anything.
 */
constraints: ConstraintReading[] }
/**
 * Which kind of Sustain to instantiate.
 * 
 * ★ A closed enum rather than a string: a template the app cannot build is
 * unrepresentable, so `instantiate` has no "unknown template" failure to
 * invent a message for.
 */
export type TemplateId = 
/**
 * The household — a parent Sustain, composed of habitats.
 */
"homestead" | 
/**
 * A person — the smallest Sustain that still holds its own money.
 */
"habitat"
/**
 * One side of a settled transfer, as the cockpit shows it.
 */
export type TransferLegDto = { sustainId: string; balanceBefore: number; balanceAfter: number }
/**
 * What the gate decided about a transfer.
 * 
 * ★★★ The two variants carry different shapes on purpose, exactly as
 * `Committed`/`Refused` do: a refusal has **no legs field at all**, so a
 * surface cannot render half a transfer by forgetting to branch.
 */
export type TransferResult = 
/**
 * ★★ `totalBefore == totalAfter` is carried, not computed by the UI —
 * conservation is the engine's claim and the screen quotes it.
 * 
 * ★ The per-variant `rename_all` is not decoration: an enum-level one
 * renames the VARIANTS and leaves struct-variant fields alone, which the
 * generated boundary caught the first time the UI read `totalBefore` and
 * got `total_before`. Exactly what the typed seam is for.
 */
{ kind: "committed"; path: string; amount: number; from: TransferLegDto; to: TransferLegDto; totalBefore: number; totalAfter: number } | { kind: "refused"; rule: string; reason: string }
/**
 * What the gate decided about one call.
 * 
 * ★★ `Refused` is a **first-class variant, not an error**. A refusal is a
 * normal, correct outcome of asking the engine to do something the household's
 * rules forbid, and modelling it as an `Err` would push it into the UI's error
 * path — where it would render as *something went wrong* rather than *the
 * system did its job*.
 */
export type Verdict = 
/**
 * Committed. The state moved.
 */
"admitted" | 
/**
 * The gate said no. **Nothing changed.**
 */
"refused" | 
/**
 * Awaiting a Council vote — not a failure, a decision not yet made.
 */
"deferred"
/**
 * What the cockpit knows about the whole household.
 */
export type WorldDto = { sustains: SustainSummary[]; selected: string | null; 
/**
 * Where the log actually lives, shown so persistence is inspectable
 * rather than a promise.
 */
storePath: string; 
/**
 * ★★ `⊕` validated by the engine (`MonitorEngine::flatten_holarchy`).
 */
holarchy: Holarchy; 
/**
 * ★ The local principal, as declared by the host.
 * 
 * ★★ **Not yet bound to anything the engine checks.** Every call still runs
 * under `Authorization::Unchecked`; this is an identity the app displays,
 * not one the gate enforces. Naming that here keeps a later capability
 * slice honest about what it is actually adding.
 */
principal: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
