// GENERATED from the Rust types by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * The household: every Sustain, the selection, and where the log lives.
 */
async getWorld() : Promise<WorldDto> {
    return await TAURI_INVOKE("get_world");
},
/**
 * `Σ` and current state for one Sustain — the selected one when `id` is absent.
 */
async getSustain(id: string | null) : Promise<SustainDto | null> {
    return await TAURI_INVOKE("get_sustain", { id });
},
/**
 * Point the cockpit at a different Sustain. `false` when there is no such id.
 */
async selectSustain(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_sustain", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Instantiate a new Sustain. `false` when the id is already taken.
 */
async createSustain(id: string, label: string, template: TemplateId, parent: string | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_sustain", { id, label, template, parent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ★★★ Ask the engine to do something on one Sustain, and report the verdict.
 * 
 * Returns `GateResult` — **not** an error type. A refusal is a correct answer,
 * and typing it as an error would make the UI render the system working as the
 * system failing.
 * 
 * `None` means there is no such Sustain, which is a different fact from a
 * refusal and is kept a different shape. The outer `Result` is for the disk.
 */
async runOperator(sustainId: string, operator: string, params: JsonValue) : Promise<Result<GateResult | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_operator", { sustainId, operator, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `V` for one Sustain, evaluated now.
 */
async getConstraints(sustainId: string) : Promise<ConstraintReading[]> {
    return await TAURI_INVOKE("get_constraints", { sustainId });
},
/**
 * ★★ The persisted log — the event log a person can read.
 * 
 * Read from **disk**, not from memory: what this shows is what actually
 * survives, which is the only version worth showing.
 */
async getLog(sustainId: string) : Promise<Result<LogEntryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log", { sustainId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every operator the given Sustain may actually run, with its **measured** cost.
 * 
 * ★★ The list is the Sustain's own `T`, not the whole registry — an operator a
 * definition does not permit would be refused with `operator_allowed`, and
 * offering it would be inviting a refusal the person could not have predicted.
 */
async getOperators(sustainId: string) : Promise<OperatorDto[]> {
    return await TAURI_INVOKE("get_operators", { sustainId });
},
/**
 * ★★★ Run a hypothetical branch. **Nothing is written.**
 * 
 * The fork is `state.clone()` plus the same `execute_admitted` a real call
 * uses, so a step refused here is refused for the same reason it would be for
 * real. It touches no log, no ledger and no meter.
 */
async simulate(sustainId: string, steps: ([string, JsonValue])[]) : Promise<Branch | null> {
    return await TAURI_INVOKE("simulate", { sustainId, steps });
},
/**
 * The whole economy, read from the engine's own ledger and parameters.
 */
async getEconomy() : Promise<EconomyDto> {
    return await TAURI_INVOKE("get_economy");
},
/**
 * ★★★ Change a governed parameter — through the gate, like anything else.
 * 
 * Returns the gate's verdict: an out-of-range value is refused with
 * `enforcement_gate`, the same reason a household breach gives.
 */
async setParameter(name: string, value: number) : Promise<GateResult> {
    return await TAURI_INVOKE("set_parameter", { name, value });
},
/**
 * Every definition a person has authored on this host.
 */
async getDefinitions() : Promise<AuthoredDefinition[]> {
    return await TAURI_INVOKE("get_definitions");
},
/**
 * ★★★ Author a definition — **the engine decides whether it lands**.
 * 
 * `editing::typecheck` parses every invariant and binds it against the schema;
 * `editing::safe` checks it against every live instance. A definition that
 * fails either is never written, and the verdict carries the engine's own
 * words rather than a summary of them.
 */
async authorDefinition(definition: AuthoredDefinition) : Promise<Result<DefinitionVerdict, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("author_definition", { definition }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Instantiate a Sustain from an authored definition — the same path a
 * built-in uses.
 */
async createFromDefinition(id: string, label: string, definitionId: string, parent: string | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_from_definition", { id, label, definitionId, parent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the local principal may do on one Sustain, **as the engine judges it**.
 * 
 * ★★ `permitted` walks the membership path with the weakest-link rule and
 * compares against each operator's declared `min_privilege`. This is the real
 * model, not a display of intentions.
 * 
 * ★★★ **And it IS what the gate checks.** Every call runs
 * `Authorization::Principal` with the unlocked identity, so this is authority
 * in force. It asks the same `permitted` the gate asks, from the same
 * memberships and the same path — a screen computing permission its own way
 * would eventually disagree with the thing that decides.
 */
async getAccess(sustainId: string) : Promise<AccessDto> {
    return await TAURI_INVOKE("get_access", { sustainId });
},
/**
 * **ρ** for one Sustain — its declared totals, folded fresh from its own state
 * and every linked child's.
 * 
 * ★ `None` only when there is no such Sustain. A Sustain that declares no
 * aggregates answers with an empty reading, because *asked for no totals* and
 * *a total that could not be computed* are different facts.
 */
async getRollup(sustainId: string) : Promise<RollupDto | null> {
    return await TAURI_INVOKE("get_rollup", { sustainId });
},
/**
 * ★★★ **The atomic, conserved cross-Sustain transfer.**
 * 
 * Both legs commit or neither does — the core makes half a transfer
 * unrepresentable, and the store's write-ahead journal makes it unwritable.
 * 
 * A refusal comes back as a **value**, not an error: the gate declining is an
 * expected outcome, and turning it into a thrown error would put it in the
 * same bucket as a disk failure.
 */
async transfer(fromSustainId: string, toSustainId: string, path: string, amount: number) : Promise<Result<TransferResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer", { fromSustainId, toSustainId, path, amount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Who this machine is, and whether the key is unlocked.
 */
async getIdentity() : Promise<IdentityDto> {
    return await TAURI_INVOKE("get_identity");
},
/**
 * **Unlock** the local identity with a passphrase.
 * 
 * ★★★ The passphrase is not compared against anything. It derives a key, and
 * either that key decrypts the private half or it does not — there is no
 * branch here an attacker could invert, and a wrong passphrase leaves the
 * world locked. The error text is the same for a wrong passphrase and a
 * tampered file, on purpose.
 */
async unlockIdentity(passphrase: string) : Promise<Result<IdentityDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_identity", { passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Enrol** a new identity on a machine that has none.
 */
async enrolIdentity(handle: string, passphrase: string) : Promise<Result<IdentityDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enrol_identity", { handle, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop the private key from memory. ★ Not a UI state — the key genuinely
 * leaves, so a locked cockpit cannot act even if a surface forgot to stop it.
 */
async lockIdentity() : Promise<IdentityDto> {
    return await TAURI_INVOKE("lock_identity");
},
/**
 * The capture queue, the declared sources, and the rules in force.
 */
async getIngest(sustainId: string) : Promise<Result<IngestDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ingest", { sustainId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Capture one message.**
 * 
 * ★★★ A message carrying a secret is refused **before anything is written**
 * — the result has no message field at all, because there is nothing to show.
 * A mapped message applies through the same gated path the Console uses, as
 * the unlocked principal.
 */
async captureMessage(sustainId: string, sourceId: string, raw: string) : Promise<Result<CaptureResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_message", { sustainId, sourceId, raw }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Has the phone been given permission to read texts yet?
 */
async smsPermissionState() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sms_permission_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ask for it. The reason is shown in the app first, before this is called.
 */
async smsRequestPermission() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sms_request_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ★★★ **`(async)` on a sync body, and it is the whole freeze fix.**
 * 
 * Tauri's macro defaults a plain `fn` command to `ExecutionContext::Blocking`,
 * which the generated handler runs INLINE on the IPC thread. On a phone that
 * is the UI thread, so a command that takes a while takes the interface with
 * it. Marking it `async` on a synchronous body selects the `sync_threadpool`
 * path instead: the same code, run off the thread that draws.
 * 
 * Found the hard way. 6,078 texts on the reporting device, 2,779 of them
 * matching, every one captured before the one call returned. The button sat
 * reading "read my texts" the entire time, and unlocking did the same thing
 * because the queue drains there.
 * 
 * ONE PAGE of the backfill. The caller loops, and shows progress between
 * pages. `since_days` of 0 means the whole inbox.
 */
async smsImportPage(sustainId: string, sinceDays: number, offset: number, limit: number) : Promise<Result<SmsSweep, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sms_import_page", { sustainId, sinceDays, offset, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ONE BATCH of whatever arrived while the app was closed. Taking clears what
 * was taken, so a text is offered once; the engine's own dedup covers the
 * rest. The caller loops while `has_more`.
 * 
 * Bounded and off the UI thread for the same reason as the page above: this
 * runs on unlock, and a queue that had built up froze the unlock itself.
 */
async smsDrainQueue(sustainId: string, limit: number) : Promise<Result<SmsSweep, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sms_drain_queue", { sustainId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * How many texts are waiting, without taking any. Cheap enough to ask before
 * deciding whether to show progress at all.
 */
async smsQueueDepth() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sms_queue_depth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Declare a capture source, optionally with the cadence it should keep.
 */
async declareSource(id: string, label: string, expectedIntervalMinutes: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("declare_source", { id, label, expectedIntervalMinutes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark a queued message as handled by a person.
 */
async resolveMessage(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_message", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Remember this format** — synthesise a rule from a confirmed correction.
 * 
 * ★★ Verified before it is ever added: it must be well-typed, must match the
 * message that taught it, and must not capture a message an existing rule
 * already handles. ★★★ A learned SPEND rule carries no operator, so a
 * correction can never teach the system to spend on someone's behalf.
 */
async learnRule(messageId: string, operator: string, params: JsonValue) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("learn_rule", { messageId, operator, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ★★★ `(async)`, because this reads the whole ingest log.
 * 
 * A sync command runs inline on the IPC thread, which on a phone is the thread
 * that draws. `get_feed` parses every stored message to find the ones still
 * waiting, and on an inbox that had been read that was thousands of them. The
 * screen froze for about a minute after unlocking, with no reading happening
 * at all: this is what it was doing.
 */
async getFeed(sustainId: string, query: string | null) : Promise<Result<FeedDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_feed", { sustainId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **`ε → (o, θ)`** — one inference pass over a narrated effect or a captured
 * message. Read-only: it resolves, it never writes.
 */
async orchieInfer(sustainId: string, messageId: string | null, effectText: string | null, known: JsonValue, ignoreHistory: boolean) : Promise<Result<InferenceDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("orchie_infer", { sustainId, messageId, effectText, known, ignoreHistory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Confirm** an inferred capture: run the operator through the real gate.
 * 
 * ★★★ The same `World::call` the Console uses, as the unlocked principal.
 * A refusal comes back as a normal verdict — an inference made at time T can
 * honestly fail at T+n if the household moved, and that is the correct
 * outcome, not an error.
 */
async orchieConfirm(sustainId: string, operator: string, params: JsonValue, messageId: string | null, description: string | null) : Promise<Result<GateResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("orchie_confirm", { sustainId, operator, params, messageId, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ★★★ Resolve a proposal with the engine's own `council::resolve`.
 * 
 * Real: the rule that a person's vote overrides the council, that an abstaining
 * person leaves it **in voting** rather than deciding, and that collected votes
 * with nobody in favour fail. None of it is re-implemented here.
 */
async resolveProposal(votes: ([string, string, number])[], userVote: string | null, votesCollected: boolean) : Promise<CouncilOutcomeDto> {
    return await TAURI_INVOKE("resolve_proposal", { votes, userVote, votesCollected });
},
/**
 * This node, its peers, and whether it is reachable at all.
 */
async getNetwork() : Promise<NetworkDto> {
    return await TAURI_INVOKE("get_network");
},
/**
 * Start accepting peers. ★ A locked node refuses, because it has nothing to
 * answer a handshake with.
 */
async startListening(port: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_listening", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a peer by key and address, without granting it anything.
 */
async addPeer(publicKey: string, handle: string, address: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_peer", { publicKey, handle, address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trust, un-trust or block a peer. ★★ Trusting is not sharing: it makes
 * sharing POSSIBLE, and each Sustain is still granted one at a time.
 */
async setPeerStanding(publicKey: string, standing: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_peer_standing", { publicKey, standing }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Share one Sustain with one peer.
 */
async shareSustain(publicKey: string, sustainId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("share_sustain", { publicKey, sustainId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Withdraw one Sustain from one peer.
 */
async unshareSustain(publicKey: string, sustainId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unshare_sustain", { publicKey, sustainId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Converge one Sustain with one peer, both directions, in one session.
 */
async syncWithPeer(address: string, sustainId: string) : Promise<Result<SyncDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_with_peer", { address, sustainId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The registry: every package, judged **now**.
 */
async getLibrary(into: string | null) : Promise<LibraryDto> {
    return await TAURI_INVOKE("get_library", { into });
},
/**
 * Publish an artifact. ★★★ The gate runs before the write.
 */
async publishPackage(request: Publication) : Promise<Result<InstallDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("publish_package", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install a package, through the same gate a local artifact faces.
 */
async installPackage(packageId: string, into: string | null) : Promise<Result<InstallDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_package", { packageId, into }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pay a package's royalty, in juul. ★★★ Internal credit. Never money.
 */
async payRoyalty(packageId: string, amount: number) : Promise<Result<RoyaltyDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pay_royalty", { packageId, amount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every shared Sustain's body, and whether it could be written to now.
 */
async getBodies() : Promise<BodyDto[]> {
    return await TAURI_INVOKE("get_bodies");
},
/**
 * Declare a Sustain co-owned by a set of node keys.
 */
async shareOwnership(sustainId: string, owners: string[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("share_ownership", { sustainId, owners }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What every trusted, addressable peer is offering.
 * 
 * ★★★ **Only peers you are connected to.** There is no index, no mesh
 * search and no global catalogue — this is exactly the list of nodes you
 * chose to peer with, and the screen says so rather than implying a market.
 */
async getPeerShelves() : Promise<PeerShelfDto[]> {
    return await TAURI_INVOKE("get_peer_shelves");
},
/**
 * Fetch one package from a peer. ★★ Records it; does **not** install it.
 */
async fetchPackage(address: string, contentHash: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_package", { address, contentHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What this node has acquired.
 */
async getOrders() : Promise<OrderDto[]> {
    return await TAURI_INVOKE("get_orders");
},
/**
 * Acquire a package: settle its royalty in **juul** and record the order.
 * 
 * ★★★ Internal credit only. Circulation is unchanged by construction —
 * `settle` transfers and never mints — and no part of this touches money.
 */
async placeOrder(packageId: string, on: number) : Promise<Result<OrderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("place_order", { packageId, on }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
committed: Committed,
refused: Refused,
rolledUp: RolledUp
}>({
committed: "committed",
refused: "refused",
rolledUp: "rolled-up"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The principal's authority over one Sustain.
 */
export type AccessDto = { principal: string; sustainId: string; 
/**
 * Effective privilege after the weakest-link path walk. `null` when the
 * principal has no membership at all.
 */
tier: number | null; memberships: number; operators: OperatorAccessDto[]; 
/**
 * ★★★ Whether the gate is currently checking any of this. It is not.
 */
enforced: boolean; note: string }
/**
 * One declared aggregate, answered by the engine.
 */
export type AggregateDto = { id: string; childPath: string; 
/**
 * `SUM` | `COUNT` | `AVG` | `MIN` | `MAX`.
 */
op: string; 
/**
 * ★ `null` for `MIN`/`MAX` over nothing — there is no smallest element of
 * an empty set, and `0` would be a claim.
 */
value: number | null; 
/**
 * ★ Whether ANYTHING was readable. `sum` over nothing is `0`, which is
 * arithmetically right and still not a measurement — a surface uses this
 * to say so rather than print a confident zero.
 */
grounded: boolean; included: ContributionDto[]; excluded: ExclusionDto[]; includesHouseholdOwn: boolean }
/**
 * One standing thing that needs a person, and why.
 */
export type AttentionDto = { kind: string; what: string; why: string; severity: string; 
/**
 * A captured message this points at, when there is one.
 */
messageId: string | null }
/**
 * A definition as authored and persisted.
 */
export type AuthoredDefinition = { id: string; label: string; dimensions: DimDecl[]; operators: string[]; invariants: InvariantDecl[]; 
/**
 * The opening state a new instance starts from.
 */
openingState: JsonValue }
/**
 * A shared Sustain's body, as the Network screen sees it.
 */
export type BodyDto = { sustainId: string; label: string; owners: CoOwnerDto[]; 
/**
 * How many must agree. Majority of the body.
 */
quorum: number; 
/**
 * How many are reachable right now, this node included.
 */
reachable: number; 
/**
 * ★★★ Whether a write could even be attempted. `false` means writes are
 * **refused**, not queued and not applied locally — the honest state
 * rather than a silent degradation.
 */
canWrite: boolean; 
/**
 * ★ The Byzantine bound for this body size, reported because a two-node
 * body tolerates **zero** traitors and a person should know that.
 */
toleratesTraitors: number; 
/**
 * The highest log position this node has agreed anything for. `None` when
 * nothing has been agreed — which is not slot zero.
 */
lastAgreed: number | null }
/**
 * A whole hypothetical branch.
 */
export type Branch = { sustainId: string; steps: BranchStep[]; 
/**
 * ★ Always true. Carried so a surface cannot render a branch without being
 * handed the fact that it is one.
 */
hypothetical: boolean; 
/**
 * The state the branch started from, for a diff.
 */
from: JsonValue }
/**
 * One step of a hypothetical branch.
 * 
 * ★★★ **Nothing here was written.** A fork is `state.clone()` plus the same
 * `execute_admitted` a real call uses, so a step refused here would be refused
 * for real — with the same reason. It touches no log, no ledger and no meter.
 */
export type BranchStep = { operator: string; verdict: Verdict; reason: string | null; constraintViolated: string | null; mutations: number; events: EventDto[]; 
/**
 * The hypothetical state after this step.
 */
state: JsonValue }
/**
 * What the classify card needs in order to show a person WHAT they are filing.
 * 
 * ★★★ The card used to ask "which pocket does this belong to?" without showing
 * the message. A person was being asked to file something they could not see.
 * Everything here was already on the ingested message; none of it was reaching
 * the screen.
 */
export type CaptureContextDto = { id: string; 
/**
 * The text exactly as it arrived.
 */
raw: string; 
/**
 * Which sender it came from: "mpesa" or "kcb".
 */
source: string; 
/**
 * What the transducer made of it, when it could.
 */
amount: number | null; counterparty: string | null; direction: string | null; 
/**
 * The transducer's own words about why this is waiting.
 */
reason: string }
/**
 * What one capture did, on the wire.
 */
export type CaptureResult = 
/**
 * ★★★ No message field at all: there is nothing to render, because
 * there was nothing to store.
 */
{ kind: "rejected"; reason: string } | { kind: "duplicate"; message: MessageDto } | { kind: "stored"; message: MessageDto }
/**
 * One card the knapsack selected, with everything a person needs to ask
 * **"why am I seeing this?"** and get a true answer.
 */
export type CardDto = { id: string; 
/**
 * What the surface should draw. An opaque tag from the declaration.
 */
render: string; 
/**
 * ★★ Salience RANK, not array index. Widgets that tie on every
 * un-gameable key share a rank, and showing one above the other as though
 * it mattered is exactly the fabricated prominence to avoid.
 */
rank: number; urgency: number; 
/**
 * ★★★ Whether that urgency was MEASURED. A `0` on an undeclared basis is
 * silence, not safety, and the card says which it is.
 */
measured: boolean; basis: string; relevance: number; score: number; cost: number; 
/**
 * Why it was eligible at all — always-on, or an event that fired.
 */
eligibility: string; 
/**
 * The operators this card may emit, from its own declaration.
 */
emits: string[] }
export type ChildStatusDto = { sustainId: string; label: string; readable: boolean }
export type ChoiceDto = { value: string; label: string }
/**
 * One co-owner of a shared Sustain, and whether this node can reach it.
 */
export type CoOwnerDto = { key: string; handle: string; 
/**
 * ★★ Reachable means *there is an address and the peer is trusted* — not
 * that a round would succeed. A surface must not promise liveness it has
 * not tested.
 */
reachable: boolean; isSelf: boolean }
/**
 * ★★★ **A committed change, pushed.** One message per real change.
 * 
 * The event *is* the message: there is no tick, no sampler and no clock,
 * because the core has none and a sampler would manufacture events nothing
 * caused. A **refusal emits nothing** — the fold stays the truth, and a
 * message saying "nothing happened" would be a change that did not happen.
 * 
 * ★★ It carries the new state as well as the events, so a subscriber is
 * correct after a single message without replaying anything. The honest cost
 * is size: a large Sustain ships its whole state per change. That is fine for
 * a household and is named in the README rather than discovered later.
 */
export type Committed = { sustainId: string; operator: string; 
/**
 * Its position in the append-only log — the same `seq` on disk.
 */
seq: number; events: EventDto[]; mutations: number; state: JsonValue; 
/**
 * `V` re-evaluated after the change, by the engine.
 */
constraints: ConstraintReading[]; liquid: number | null }
/**
 * One invariant, evaluated against current state **by the engine**.
 * 
 * ★★ `holds` and `reason` come from `sustena_core::predicate::check`, the same
 * evaluator the gate uses. The host does not judge a rule; it asks.
 */
export type ConstraintReading = { id: string; expression: string; holds: boolean; 
/**
 * ★ Empty when it holds; otherwise the engine's own words, naming the
 * operand and the value that failed.
 */
reason: string }
/**
 * One contributor to a household total.
 * 
 * ★★ `isHousehold` is a real distinction, not decoration: a surface has to be
 * able to say *the household's own 6,600 plus six members* rather than listing
 * seven anonymous numbers, and inferring it by comparing ids would be the kind
 * of guess this layer exists to remove.
 */
export type ContributionDto = { sustainId: string; 
/**
 * The member's name, else the slot, else the id.
 */
label: string; isHousehold: boolean; value: number }
/**
 * What `council::resolve` decided.
 */
export type CouncilOutcomeDto = { 
/**
 * `Passed` | `Failed` | `InVoting` | `OverriddenByUser` | …
 */
status: string; 
/**
 * The councillor's single vote after `aggregate_delegated_votes`.
 */
aggregated: string; 
/**
 * The engine's own explanation of the aggregation.
 */
reasoning: string; utility: number; counted: number }
/**
 * What the engine said about an authored definition.
 */
export type DefinitionVerdict = 
/**
 * `typecheck` accepted it, and no live instance would be stranded.
 */
{ kind: "accepted" } | 
/**
 * ★ One entry per problem, each naming the invariant and the detail —
 * `editing::typecheck`'s own words, not a summary of them.
 */
{ kind: "notWellTyped"; errors: string[] } | 
/**
 * ★★ Live Sustains this edit would push outside their viable region —
 * each with the RULE it would break and the engine's reason. A refusal
 * that cannot say which sustain and which rule is an alarm, not a
 * diagnosis.
 */
{ kind: "wouldStrand"; instances: string[] }
/**
 * One dimension a person declared.
 */
export type DimDecl = { path: string; 
/**
 * `number` | `text` | `bool` | `any`.
 */
kind: string; 
/**
 * ★ Optional bounds for a number. `DimType::Number` carries them, so a
 * dimension can be constrained at the SCHEMA level as well as by an
 * invariant — two different questions: what values are representable, and
 * what values are viable.
 */
lo: number | null; hi: number | null }
/**
 * The whole economy, as one screen reads it.
 */
export type EconomyDto = { principal: string; balance: number; 
/**
 * `Sigma(mints) - Sigma(debits)`, transfers at zero.
 */
circulation: number; mintedTotal: number; issuedTotal: number; genesisId: string; genesisTotal: number; 
/**
 * ★ The audit is the engine's, not the host's: it names foreign mints,
 * mismatched allocations and undeclared principals rather than returning a
 * boolean.
 */
auditClean: boolean; auditDescribes: string; entries: LedgerEntryDto[]; parameters: ParameterDto[]; 
/**
 * Every reading the meter has taken, by operator.
 */
metered: ([string, MeasuredPawa])[]; 
/**
 * ★★★ The permanent boundary, carried as data so a surface cannot forget
 * to show it.
 */
boundaryNotice: string }
/**
 * One event the call published.
 * 
 * ★ `PartialEq` because a log line is compared for equality by the
 * replicated log: two nodes claiming one stamp must be told apart by their
 * CONTENT, and that comparison reaches all the way down.
 */
export type EventDto = { name: string; payload: JsonValue }
/**
 * A contributor that could NOT be read, and the engine's own reason.
 * 
 * ★★★ This is the honest-exclusion contract on the wire. A total that dropped
 * a member silently would be indistinguishable from one where that member
 * genuinely holds nothing — so the exclusions travel with the value, and a
 * screen showing one without the other is misreporting on its own account.
 */
export type ExclusionDto = { sustainId: string; label: string; isHousehold: boolean; reason: string }
/**
 * The whole curated view.
 */
export type FeedDto = { sustainId: string; label: string; cards: CardDto[]; 
/**
 * The oldest capture still needing a person, if there is one.
 * 
 * ★★ ONE message rather than a list. The classify card works the queue one
 * at a time; a list here would be the unbounded second surface the
 * attention budget exists to prevent.
 */
queueHead: CaptureContextDto | null; 
/**
 * ★ What stayed quiet — withdrawn and excluded alike, each saying which.
 */
quiet: QuietDto[]; budget: number; spent: number; candidatesConsidered: number; 
/**
 * The projection `compose` reasoned over — exposed so a card can render
 * the very numbers it was ranked on.
 */
reading: JsonValue; attention: AttentionDto[]; 
/**
 * The calm read: the household's own roll-up ρ, when it declares one.
 */
rollup: RollupDto | null; liquid: number | null }
/**
 * The gate's own words about one call.
 */
export type GateResult = { verdict: Verdict; 
/**
 * The operator that was asked for.
 */
operator: string; 
/**
 * ★ The refusal reason, **as the engine wrote it**. Never re-phrased here:
 * the engine names the rule and the numbers, and a host that softened that
 * into "could not complete" would be hiding the only useful part.
 */
reason: string | null; 
/**
 * Which rule refused it — a guard expression, or `enforcement_gate`.
 */
constraintViolated: string | null; 
/**
 * Empty on a refusal, always — a refusal changes nothing.
 */
mutations: number; events: EventDto[]; 
/**
 * The resulting state, or the **untouched original** if refused.
 */
state: JsonValue; 
/**
 * ★★★ What the operator returned alongside its verdict.
 * 
 * A refusal from `budget.spend` carries `remaining`, `requested` and
 * `shortfall`, put there so a caller can build an allocate-then-retry
 * without reading an English sentence. It was being dropped here, which
 * left the surface with a dead end and a paragraph.
 */
data: JsonValue }
/**
 * Whether the composition tree holds, **as the engine judges it**.
 * 
 * ★ A sum type rather than a bool: a tree that does not hold should say which
 * link broke it, and a `false` with the reason thrown away is an alarm rather
 * than a diagnosis.
 */
export type Holarchy = 
/**
 * `MonitorEngine::flatten_holarchy` accepted it — no duplicate id, no
 * unknown parent, no cycle.
 */
{ kind: "holds"; linked: number } | 
/**
 * It refused, and here is what it said.
 */
{ kind: "broken"; reason: string }
/**
 * Who this machine is, and whether the key is in memory.
 * 
 * ★★ `handle` is readable while LOCKED — a person should be able to see which
 * identity they are being asked to unlock. `publicKey` is not: it is derived
 * from the private half, and having it means the unlock genuinely happened.
 */
export type IdentityDto = { 
/**
 * Whether an identity exists on this machine at all.
 */
enrolled: boolean; 
/**
 * Whether the private key is in memory right now.
 */
unlocked: boolean; handle: string | null; 
/**
 * The verifying key, hex — present only once unlocked.
 */
publicKey: string | null; 
/**
 * The KDF actually in force, named rather than assumed.
 */
kdf: string | null; iterations: number | null }
/**
 * One inference pass, on the wire.
 */
export type InferenceDto = { status: "ready"; operator: string; params: JsonValue; why: string; description: string | null; fromHistory: boolean; historyUseCount: number | null } | 
/**
 * ★ `options: null` means the answer is not a tap — render an input.
 */
{ status: "needsDisambiguation"; field: string; question: string; options: ChoiceDto[] | null; why: string } | { status: "cannotInfer"; why: string }
/**
 * The whole ingest picture for one Sustain.
 */
export type IngestDto = { messages: MessageDto[]; sources: SourceDto[]; rules: RuleDto[]; 
/**
 * ★★★ How many messages were refused for carrying a secret. A COUNT,
 * and nothing else — the messages themselves were never written.
 */
rejected: number; needsAttention: number }
/**
 * What one install attempt did.
 */
export type InstallDto = { 
/**
 * `admitted` | `refused` | `not_here`.
 */
outcome: string; 
/**
 * The gate that refused, by its own name. Empty when admitted.
 */
rule: string; 
/**
 * The gate's own words.
 */
errors: string[]; provenance: string; 
/**
 * The artifact's id once applied.
 */
applied?: string | null; summary: string }
/**
 * One rule a person declared.
 */
export type InvariantDecl = { id: string; expression: string }
/**
 * A rule the household declared it must stay within.
 */
export type InvariantDto = { id: string; expression: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * One line of the juul ledger.
 * 
 * ★★ The **kind** is the entry's own variant, not a sign on a number: a mint
 * names the declaration that authorised it, a debit names the run it paid for,
 * a transfer names both ends. Collapsing them would make *where did this juul
 * come from* unanswerable.
 */
export type LedgerEntryDto = { 
/**
 * `mint` | `debit` | `transfer`.
 */
kind: string; principal: string; counterparty: string | null; amount: number; 
/**
 * For a mint: the declaration that authorised it. For a debit: the operator.
 */
authority: string; 
/**
 * Its effect on total circulation — `+` for a mint, `-` for a debit, `0` for a transfer.
 */
circulationDelta: number }
/**
 * The registry, and what this node could publish into it.
 */
export type LibraryDto = { packages: PackageDto[]; 
/**
 * Definitions authored here that are not published yet.
 */
publishable: ([string, string])[]; 
/**
 * Sustains a widget could be installed into.
 */
targets: ([string, string])[]; 
/**
 * ★ A locked node cannot sign, so it cannot publish. Said rather than
 * shown as an idle button.
 */
unlocked: boolean }
/**
 * One line of the persisted log, as a person reads it.
 */
export type LogEntryDto = { seq: number; 
/**
 * The operator that caused it, or `genesis` for the opening line.
 */
operator: string; events: EventDto[]; 
/**
 * ★ How many state changes it carried. The mutations themselves stay on
 * disk — a log view is for reading what happened, and a wall of paths is
 * not that.
 */
mutations: number }
/**
 * What the meter has actually measured for an operator.
 * 
 * ★★★ `None` means **not measured**, and the UI must say so rather than
 * showing a zero. A `0` from an unmeasured basis is silence, not cheapness.
 */
export type MeasuredPawa = { runs: number; meanPawa: number; totalPawa: number; totalCompute: number; totalStorage: number }
/**
 * One captured message.
 * 
 * ★★★ A REJECTED message never appears here, because it never reached the
 * store. The queue counts them and holds none of them.
 */
export type MessageDto = { id: string; sourceId: string; 
/**
 * `mapped` | `parsed_unmapped` | `informational` | `unparsed`.
 */
status: string; 
/**
 * Which declared rule handled it — empty when none did.
 */
parserName: string; 
/**
 * The engine's own words about why this is what it is.
 */
reason: string; 
/**
 * The raw text. Retained deliberately: a person correcting a
 * classification needs to see what actually arrived.
 */
rawPayload: string; amount: number | null; counterparty: string | null; direction: string | null; externalRef: string | null; operator: string | null; applied: boolean; 
/**
 * What the gate said, when a mapped message was refused.
 */
gateReason: string | null; resolved: boolean; needsAttention: boolean }
/**
 * This node on the network.
 */
export type NetworkDto = { 
/**
 * This node's own public key, readable while locked — it is public.
 */
nodeId: string | null; handle: string | null; 
/**
 * The port this node accepts peers on. `None` means **not listening**,
 * which a `0` would have read as a port.
 */
listening: number | null; 
/**
 * ★★ A locked node cannot prove its own key, so it cannot peer at all.
 * The screen says which, rather than showing an idle network.
 */
unlocked: boolean; peers: PeerDto[]; 
/**
 * The wire protocol this node speaks. ★★★ Reported rather than a padlock:
 * a version is checkable, and a padlock that is always green regardless
 * is worse than none.
 */
protocol: number; 
/**
 * What a session actually provides, in the words of what was built.
 */
session: string; 
/**
 * Sustains this node could offer — `(id, label)`. An authored definition
 * is absent, because v1 shares built-in templates only.
 */
shareable: ([string, string])[] }
/**
 * One package a peer says it holds. ★ A listing, never the artifact.
 */
export type OfferDto = { id: string; name: string; kind: string; version: string; description: string; author: string; authorHandle: string; contentHash: string; 
/**
 * ★★ Shown **before** fetching, so authorship is a thing you decide on
 * rather than discover afterwards.
 */
signed: boolean; 
/**
 * Whether this node already holds these exact bytes.
 */
alreadyHere: boolean }
/**
 * Whether the principal may run one operator, as the engine judges it.
 */
export type OperatorAccessDto = { operator: string; 
/**
 * The operator's declared `min_privilege`. ★ Lower is more privileged:
 * 0 = owner, 3 = observer.
 */
requiredTier: number; permitted: boolean; 
/**
 * The engine's own denial text when it is not.
 */
denial: string | null }
/**
 * One operator the selected Sustain may actually run.
 */
export type OperatorDto = { name: string; description: string; params: ParamDto[]; 
/**
 * The author's declared estimate. ★ Kept beside the measurement precisely
 * so the two can be compared — the reference's estimate is usually 0.
 */
declaredPawa: number; 
/**
 * ★ `null` when the meter has never seen it run.
 */
measured: MeasuredPawa | null; sideEffects: string[] }
/**
 * One acquisition. ★★★ `paid` is **juul**, this host's internal unit —
 * never money, never off this host, never a rail.
 */
export type OrderDto = { reference: string; packageId: string; packageName: string; by: string; paid: number; perMille: number; 
/**
 * `(role, recipient, amount)` — every share, including ones that stayed
 * where they already were.
 */
shares: ([string, string, number])[]; placedAt: string }
/**
 * One published package, as a screen sees it.
 */
export type PackageDto = { id: string; name: string; 
/**
 * `definition` | `widget` | `operator` | `strategy`.
 */
kind: string; version: string; description: string; tags: string[]; 
/**
 * The author's key, and the label they chose beside it. ★ The key is the
 * identity; the handle is a label and the surface says so.
 */
author: string; authorHandle: string; contentHash: string; 
/**
 * ★★★ The three questions, kept apart all the way to the screen.
 */
integrity: string; authenticity: string; origin: string; 
/**
 * One line, in the engine's own words.
 */
provenance: string; 
/**
 * Royalty in **juul** per mille — the internal unit, never money.
 */
perMille: number; 
/**
 * Whether this node has installed it, and into what.
 */
installed: boolean; installedInto?: string | null; 
/**
 * ★★★ The trust band: `unrated` | `repudiated` | `thin` |
 * `corroborated` | `first-hand`. **`unrated` is not a low score** — it
 * means nothing is known, and a surface must not render it on the same
 * scale as the others.
 */
trust: string; 
/**
 * Whether `trust` may be shown as a reading at all. `false` for
 * `unrated`.
 */
trustIsAReading: boolean; 
/**
 * The facts the band was composed from, each in its own words. ★ A band
 * without its reasons is the reference's float with a nicer name.
 */
trustSignals: string[]; 
/**
 * ★★ What the gate says about installing it **right now** — recomputed,
 * not remembered. A package that was fine yesterday can be refused today
 * because a live instance moved.
 */
verdict: string; installable: boolean }
/**
 * One parameter an operator declares.
 * 
 * ★★ **Declared by the operator, not guessed by the UI.** `ParamDecl` carries
 * the name, the kind, whether it is required, and — for a naming parameter —
 * the state path whose KEYS are the legal values. So a picker can offer real
 * pocket names without this app knowing what a pocket is.
 */
export type ParamDto = { name: string; 
/**
 * `number` | `text` | `any`.
 */
kind: string; required: boolean; 
/**
 * A state path whose keys are the legal values, when the operator declares one.
 */
namesWithin: string | null }
/**
 * One governed parameter and its declared bounds.
 */
export type ParameterDto = { name: string; value: number; genesis: number; min: number; max: number }
/**
 * One peer, as a screen sees it.
 */
export type PeerDto = { 
/**
 * ★ The identity. The handle beside it is a label the peer chose.
 */
publicKey: string; handle: string; 
/**
 * `host:port`, or `None` for a peer that reached in and was never given
 * an address to dial back. **Not** an empty string — unreachable and
 * "reachable at nowhere" are different facts.
 */
address: string | null; 
/**
 * `pending` | `trusted` | `blocked`.
 */
standing: string; 
/**
 * Sustains this node has shared WITH this peer. Never what the peer holds
 * — this node cannot know that.
 */
shares: string[]; 
/**
 * Seconds since the epoch at the last completed sync, as a string
 * because a 64-bit integer would cross the boundary as a `BigInt`.
 * `None` means **never synced**, which is not zero.
 */
lastSynced: string | null; lastError: string | null }
/**
 * What one peer is offering, or why nothing could be listed.
 */
export type PeerShelfDto = { peer: string; handle: string; address: string; packages: OfferDto[]; 
/**
 * ★★★ The honest failure. A peer that could not be reached says so;
 * it does not appear as a peer with nothing to offer.
 */
unreachable?: string | null }
/**
 * A pocket, at summary scale.
 * 
 * ★ Small on purpose. The Constellation reads summaries for every Sustain and
 * hydrates full state only on drill-in, so this carries the three numbers a
 * vitals reading needs and not the document they came from.
 */
export type PocketSummary = { name: string; allocated: number; spent: number }
/**
 * What a person is asking to publish, before it is stamped or judged.
 * 
 * ★ One struct rather than nine parameters: the metadata travels together
 * everywhere it goes — the form, the command, the store — so it may as well
 * be one thing.
 */
export type Publication = { name: string; 
/**
 * ★ A string at the boundary, parsed by `Kind::parse` — `Kind` is a core
 * type and specta is a host dependency, so the enum cannot cross as
 * itself. An unknown kind is refused rather than defaulted.
 */
kind: string; version: string; description?: string; tags?: string[]; spec: JsonValue; 
/**
 * The royalty rate in **juul** per mille. `0` is [`Licence::Free`].
 */
perMille?: number; 
/**
 * The Sustain a widget would join. Required for a widget, meaningless
 * for a definition — see `World::judge`.
 */
into?: string | null }
/**
 * A card that withdrew before ranking.
 * 
 * ★★ Distinct from an exclusion: an excluded card was **considered and
 * outranked** and carries a score; a withdrawn one had **nothing to say** and
 * carries a reason, because no score was ever computed.
 */
export type QuietDto = { id: string; 
/**
 * A reason for a withdrawal; a score for an exclusion. Never both.
 */
reason: string | null; score: number | null; withdrew: boolean }
/**
 * ★★★ **A refusal, pushed — and it carries NO STATE.**
 * 
 * A separate type from [`Committed`] on purpose. The two answer different
 * questions: *what changed* and *what was asked and declined*. Collapsing them
 * into one message with a verdict flag would make it possible for a consumer
 * to treat a refusal as a change by forgetting to branch — here there is no
 * `state` field to read, so that mistake is unspellable.
 * 
 * ★★ This does not weaken V1.2's rule. **A refusal still emits no state
 * delta**; the fold is still the only truth about state. What travels here is
 * the *activity*: a request happened and the gate declined it, which a person
 * watching a household genuinely wants to see.
 */
export type Refused = { sustainId: string; operator: string; 
/**
 * The engine's own words.
 */
reason: string | null; 
/**
 * Which rule declined it.
 */
constraintViolated: string | null }
/**
 * ★★★ **A household total, recomputed and pushed.**
 * 
 * A THIRD typed event, for the same reason there is a second: it answers a
 * third question. `Committed` says *what changed, in the Sustain that
 * changed*; ρ is a **different Sustain's** derived reading, and folding it
 * into `Committed` would mean a message about Bonnie's habitat carrying the
 * homestead's state under a field name that did not say so.
 * 
 * ★★ It is emitted only after a real commit, only for a Sustain that actually
 * declares aggregates. A refusal emits nothing here either — ρ is a function
 * of state, and a refused call changed no state, so the total it would carry
 * is the one the subscriber already has.
 */
export type RolledUp = { rollup: RollupDto }
/**
 * **ρ** for one parent, computed fresh.
 * 
 * ★ `declared` is empty for a Sustain that asked for no totals — which is a
 * different fact from *a total that could not be computed*, and the two must
 * not render the same.
 */
export type RollupDto = { sustainId: string; aggregates: AggregateDto[]; 
/**
 * Linked children, and whether each was readable at all.
 */
children: ChildStatusDto[] }
/**
 * What a royalty moved. ★★★ In **juul**, always.
 */
export type RoyaltyDto = { 
/**
 * `settled` | `no_royalty` | `insufficient`.
 */
outcome: string; transferred: number; 
/**
 * `(role, recipient, amount)` — every share, including the ones that
 * stayed put.
 */
shares: ([string, string, number])[]; 
/**
 * ★★★ Total juul across every balance, before and after. Equal, always:
 * a royalty transfers and never mints.
 */
circulationBefore: string; circulationAfter: string }
/**
 * One declared parse rule, for the library view.
 */
export type RuleDto = { id: string; source: string; version: number; 
/**
 * `mapped` | `parsed_unmapped` | `informational`.
 */
status: string; operator: string | null; 
/**
 * `shipped` | `user_corrected` | `proposed_confirmed`.
 */
trust: string; examples: number }
/**
 * What one sweep did. Every number is counted from a real outcome.
 */
export type SmsSweep = { 
/**
 * Read off the phone and offered to the engine.
 */
read: number; 
/**
 * Understood and routed on their own. Income only.
 */
applied: number; 
/**
 * Understood, and waiting for a person to say which pocket.
 */
needsYou: number; 
/**
 * Seen before. Captured once, counted here, changed nothing.
 */
duplicates: number; 
/**
 * No rule recognised the shape.
 */
unparsed: number; 
/**
 * Carried a one-time code. Nothing about them was stored.
 */
refused: number; 
/**
 * Read on the phone and dropped there: not from M-Pesa or KCB.
 */
skippedOtherSenders: number; 
/**
 * Dropped on the phone as a one-time code, before reaching this side.
 */
skippedSecrets: number; 
/**
 * A text the engine refused outright, with the first reason.
 */
failed: number; firstFailure: string | null; 
/**
 * Another page or batch is waiting.
 */
hasMore: boolean; 
/**
 * Where the next page starts. Reading only.
 */
nextOffset: number; 
/**
 * Still queued after this batch. Draining only.
 */
remaining: number }
/**
 * A declared capture source.
 */
export type SourceDto = { id: string; label: string; captures: number; 
/**
 * ★ `null` when this source declared no cadence — and then `stale` is
 * `false`, never a guess.
 */
expectedIntervalMinutes: number | null; everSeen: boolean }
/**
 * One value a concurrent write overwrote.
 */
export type SupersededDto = { path: string; winner: string; loser: string }
/**
 * `Σ = ⟨B, S, V, T, ⊕⟩`, as much of it as a cockpit needs to draw.
 * 
 * ★ Deliberately not the whole `Definition`: a walking skeleton should carry
 * what it actually renders, and inventing fields the UI does not use yet would
 * be publishing a contract nobody has tested.
 */
export type SustainDto = { id: string; label: string; 
/**
 * `T` — the moves this Sustain may make.
 */
operators: string[]; 
/**
 * `V` — the viable region.
 */
invariants: InvariantDto[]; 
/**
 * Whether the gate is armed for it.
 */
gateArmed: boolean; 
/**
 * `S` — current state.
 */
state: JsonValue }
/**
 * One Sustain, as a selector row needs it.
 * 
 * ★ Deliberately not the full `SustainDto`: a list of six should not carry six
 * full state documents, and a shape that made it easy to would invite it.
 */
export type SustainSummary = { id: string; label: string; template: TemplateId; 
/**
 * `⊕` — its parent, if it has one.
 */
parent: string | null; 
/**
 * How many events its log holds. ★ The real number, folded from disk —
 * this is what makes persistence visible rather than claimed.
 */
events: number; 
/**
 * Its liquid balance, or `null` when the Sustain declares no such
 * dimension. **Never 0 for absent** — a missing figure renders as "—".
 */
liquid: number | null; 
/**
 * Its pockets, at summary scale.
 */
pockets: PocketSummary[]; 
/**
 * ★★ `V` for THIS Sustain, evaluated by the engine — so a constellation
 * can show a broken rule anywhere without hydrating anything.
 */
constraints: ConstraintReading[] }
/**
 * What one sync did, and what the merge could not decide.
 */
export type SyncDto = { peer: string; handle: string; sustainId: string; received: number; sent: number; entries: number; 
/**
 * Pairs neither of which happened before the other.
 */
concurrent: number; 
/**
 * ★★★ Values a concurrent write overwrote. **Every entry survives; these
 * values did not.** Named rather than dropped.
 */
superseded: SupersededDto[]; 
/**
 * Stamps that arrived carrying two payloads — a node forking its history.
 */
forks: number; 
/**
 * ★★★ Whether the merged state still satisfies the Sustain's own rules.
 * `None` = unmeasured (no armed enforcement), which is not *fine*.
 */
admissible: boolean | null; 
/**
 * `(id, why)` for each rule the merged state breaks.
 */
violated: ([string, string])[]; 
/**
 * One line, in the engine's own words.
 */
summary: string }
/**
 * Which kind of Sustain to instantiate.
 * 
 * ★ A closed enum rather than a string: a template the app cannot build is
 * unrepresentable, so `instantiate` has no "unknown template" failure to
 * invent a message for.
 */
export type TemplateId = 
/**
 * The household — a parent Sustain, composed of habitats.
 */
"homestead" | 
/**
 * A person — the smallest Sustain that still holds its own money.
 */
"habitat"
/**
 * One side of a settled transfer, as the cockpit shows it.
 */
export type TransferLegDto = { sustainId: string; balanceBefore: number; balanceAfter: number }
/**
 * What the gate decided about a transfer.
 * 
 * ★★★ The two variants carry different shapes on purpose, exactly as
 * `Committed`/`Refused` do: a refusal has **no legs field at all**, so a
 * surface cannot render half a transfer by forgetting to branch.
 */
export type TransferResult = 
/**
 * ★★ `totalBefore == totalAfter` is carried, not computed by the UI —
 * conservation is the engine's claim and the screen quotes it.
 * 
 * ★ The per-variant `rename_all` is not decoration: an enum-level one
 * renames the VARIANTS and leaves struct-variant fields alone, which the
 * generated boundary caught the first time the UI read `totalBefore` and
 * got `total_before`. Exactly what the typed seam is for.
 */
{ kind: "committed"; path: string; amount: number; from: TransferLegDto; to: TransferLegDto; totalBefore: number; totalAfter: number } | { kind: "refused"; rule: string; reason: string }
/**
 * What the gate decided about one call.
 * 
 * ★★ `Refused` is a **first-class variant, not an error**. A refusal is a
 * normal, correct outcome of asking the engine to do something the household's
 * rules forbid, and modelling it as an `Err` would push it into the UI's error
 * path — where it would render as *something went wrong* rather than *the
 * system did its job*.
 */
export type Verdict = 
/**
 * Committed. The state moved.
 */
"admitted" | 
/**
 * The gate said no. **Nothing changed.**
 */
"refused" | 
/**
 * Awaiting a Council vote — not a failure, a decision not yet made.
 */
"deferred"
/**
 * What the cockpit knows about the whole household.
 */
export type WorldDto = { sustains: SustainSummary[]; selected: string | null; 
/**
 * Where the log actually lives, shown so persistence is inspectable
 * rather than a promise.
 */
storePath: string; 
/**
 * ★★ `⊕` validated by the engine (`MonitorEngine::flatten_holarchy`).
 */
holarchy: Holarchy; 
/**
 * ★ The local principal, as declared by the host.
 * 
 * ★★ **Not yet bound to anything the engine checks.** Every call still runs
 * under `Authorization::Unchecked`; this is an identity the app displays,
 * not one the gate enforces. Naming that here keeps a later capability
 * slice honest about what it is actually adding.
 */
principal: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
