// GENERATED from the Rust types by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * `Σ` and its current state.
 */
async getSustain() : Promise<SustainDto> {
    return await TAURI_INVOKE("get_sustain");
},
/**
 * ★★★ Ask the engine to do something, and report what the gate decided.
 * 
 * Returns `GateResult` — **not** `Result<_, String>`. A refusal is a correct
 * answer, and typing it as an error would make the UI render the system
 * working as the system failing.
 */
async runOperator(operator: string, params: JsonValue) : Promise<GateResult> {
    return await TAURI_INVOKE("run_operator", { operator, params });
},
/**
 * Start over from the opening state.
 */
async resetSustain() : Promise<SustainDto> {
    return await TAURI_INVOKE("reset_sustain");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * One event the call published.
 */
export type EventDto = { name: string; payload: JsonValue }
/**
 * The gate's own words about one call.
 */
export type GateResult = { verdict: Verdict; 
/**
 * The operator that was asked for.
 */
operator: string; 
/**
 * ★ The refusal reason, **as the engine wrote it**. Never re-phrased here:
 * the engine names the rule and the numbers, and a host that softened that
 * into "could not complete" would be hiding the only useful part.
 */
reason: string | null; 
/**
 * Which rule refused it — a guard expression, or `enforcement_gate`.
 */
constraintViolated: string | null; 
/**
 * Empty on a refusal, always — a refusal changes nothing.
 */
mutations: number; events: EventDto[]; 
/**
 * The resulting state, or the **untouched original** if refused.
 */
state: JsonValue }
/**
 * A rule the household declared it must stay within.
 */
export type InvariantDto = { id: string; expression: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * `Σ = ⟨B, S, V, T, ⊕⟩`, as much of it as a cockpit needs to draw.
 * 
 * ★ Deliberately not the whole `Definition`: a walking skeleton should carry
 * what it actually renders, and inventing fields the UI does not use yet would
 * be publishing a contract nobody has tested.
 */
export type SustainDto = { id: string; label: string; 
/**
 * `T` — the moves this Sustain may make.
 */
operators: string[]; 
/**
 * `V` — the viable region.
 */
invariants: InvariantDto[]; 
/**
 * Whether the gate is armed for it.
 */
gateArmed: boolean; 
/**
 * `S` — current state.
 */
state: JsonValue }
/**
 * What the gate decided about one call.
 * 
 * ★★ `Refused` is a **first-class variant, not an error**. A refusal is a
 * normal, correct outcome of asking the engine to do something the household's
 * rules forbid, and modelling it as an `Err` would push it into the UI's error
 * path — where it would render as *something went wrong* rather than *the
 * system did its job*.
 */
export type Verdict = 
/**
 * Committed. The state moved.
 */
"admitted" | 
/**
 * The gate said no. **Nothing changed.**
 */
"refused" | 
/**
 * Awaiting a Council vote — not a failure, a decision not yet made.
 */
"deferred"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
